import type { Copy } from "./types";

export const en: Copy = {
  lang: "en",
  nav: { work: "Portfolio", services: "Services", about: "Who & why", contact: "Contact" },
  routes: { services: "services", about: "about", contact: "contact", portfolio: "portfolio" },
  portfolio: { eyebrow: "What we've made", h: "Every project here was built with one thought: this has to stick.", hint: "Click a project to open the site.", live: "Live", wip: "In the works", visit: "Open the site", meta: "Websites and campaigns by Defy & Brand Events: Rhumerie Louis, AI in de klas, DPODR, EcoClean Luxembourg, Karweiservice Vanden Berghe, Oostende.ai, Customm." },
  meta: {
    title: "Defy & Brand Events — We turn ideas into experiences",
    description:
      "Defy & Brand Events turns ideas into brands, websites, campaigns and AI-ready experiences that move people. Strategy, creativity and technology in one team.",
  },
  home: {
    heroLead: "We turn ideas into experiences.",
    heroIntro:
      "An idea is nothing until someone feels it. We build brands, websites, campaigns and words that create that moment: the one where a person stops, looks, gets it — and chooses.",
    heroCta: "Show us what you're thinking",
    statement: [
      "Not an agency with a menu.",
      "One team that thinks, makes, tests and improves — until the idea does what it was meant to do.",
    ],
    manifesto: "An idea is nothing until someone feels it.",
    manifestoAfter: "We turn ideas into experiences.",
    servicesEyebrow: "Nine services. One movement.",
    servicesHint: "Scroll to rotate",
    chainEyebrow: "From idea to action",
    chain: [
      { h: "An idea", p: "Strategy sets the direction. Brand & Creative gives the idea its shape." },
      { h: "becomes a brand", p: "Copywriting gives it a voice. Website Design builds the digital experience." },
      { h: "becomes an experience", p: "Marketing brings the right people to it. SEO makes you findable, GEO makes you understandable to AI." },
      { h: "becomes action", p: "Agent Ready makes you ready for AI agents. Agentic Workflow lets technology actually act." },
    ],
    chainNote: "That's what we mean by Events. Not a venue and a stage. The moment everything comes together and someone moves.",
    closerH: "You have an idea. We turn it into something people feel.",
    closerCta: "Let's make it happen",
  },
  about: {
    eyebrow: "Why we exist",
    h: "We don't build brands. We build the moment someone cares.",
    why: [
      "We've watched too many good ideas die.",
      "In a deck nobody opened again. In a strategy with nobody to execute it. In a campaign that was “creative” and nothing else. In a website that looked stunning and did nothing.",
      "Defy & Brand was founded out of impatience with that pattern.",
    ],
    notTitle: "What we don't do",
    not: [
      "No one-size-fits-all. Your brand doesn't need a template, it needs an answer.",
      "No ideas that disappear into a drawer. If we think it, we build it.",
      "No strategy without execution. A plan that never gets built is an opinion.",
      "No creativity for creativity's sake. If it means nothing, it does nothing.",
    ],
    howTitle: "How we work",
    verbs: ["We think.", "We make.", "We test.", "We improve.", "We bring ideas to life."],
    howNote: "In that order, then again. Small team, short lines, no layers. You talk to the people who do the work.",
    nameTitle: "Defy & Brand — the name",
    name: [
      { k: "Defy", p: "is refusing to do what everyone in your sector does, just because everyone does it." },
      { k: "Brand", p: "is the discipline that gives that nerve a direction." },
      { k: "Events", p: "is what happens when it works: an experience that touches someone and gets them moving." },
    ],
    cta: "Get to know us",
    meta: "Why Defy & Brand Events exists: no one-size-fits-all, no strategy without execution. We think, make, test, improve and bring ideas to life.",
  },
  contact: {
    pickEyebrow: "What is it about?",
    pickH: "Pick what you want to talk about.",
    pickP: "Tap a service and it lands in the form as the subject. Not sure yet? Skip it — just telling us works too.",
    subject: "Subject",
    other: "Something else / not sure yet",
    detailsH: "Direct",
    phone: "Call",
    mail: "Mail",
    visit: "Drop by",
    h: "There's something in your head. Let's get it out.",
    lines: [
      "An idea that doesn't have a shape yet.",
      "A problem you've been staring at for too long.",
      "An ambition that's bigger than your current website.",
      "A project that needs to go somewhere — and doesn't know where yet.",
    ],
    invite: "You don't have to have it figured out. You just have to tell us.",
    talk: "Let's make some noise.",
    labels: {
      who: "Who are you?",
      reach: "How do we reach you?",
      what: "What's on your mind? (Rough is fine. Rough is usually best.)",
      send: "Send it",
    },
    confirm: "Received. We actually read it, and you'll hear from our team within two working days — not an autoresponder.",
    alt: "Rather talk right now?",
    meta: "An idea, a problem, an ambition? Tell Defy & Brand Events. You don't have to have it figured out.",
    cine: {
      eyebrow: "The creative behind the ideas",
      name: "ThinkRebel",
      role: "Njusja Orban — Creative",
      quote: "Some ideas need a strategy. Others just need someone crazy enough to make them happen.",
      have: "Have an idea?",
      make: "Let's make it happen.",
      tell: "Tell us what you're thinking. We'll figure out what to do with it.",
      cta: "Let's make some noise",
    },
  },
  footer: { tagline: "We turn ideas into experiences.", another: "Got another idea? Let's make some noise." },
  services: [
    {
      slug: "strategy",
      num: "01",
      name: "Strategy",
      role: "sets the direction",
      headline: "Strategy meets creativity. That's where the magic happens.",
      intro: [
        "Creativity without strategy becomes noise. Strategy without creativity becomes boring.",
        "We don't choose between the two. We bring them together — and that's where it happens.",
      ],
      blocksTitle: "What strategy is about",
      blocks: [
        { h: "Positioning", p: "What are you that nobody else is? And do you dare to say it? We look for the space in your customer's mind that's still free — and claim it." },
        { h: "Brand strategy", p: "Why you exist, what you promise and how you consistently deliver on it. The basis every creative idea gets tested against." },
        { h: "Marketing strategy", p: "Who, when, where and with what message. Not everything for everyone. The right thing for the right people." },
        { h: "Digital strategy", p: "What role do your website, your content, your data, AI play? Not “because we have to”, but because it gives your customer something." },
        { h: "Audience and customer journey", p: "How does someone really decide? Where do they hesitate, where do they drop off, where do you win them? We map the path and build on the points that make the difference." },
        { h: "Direction and growth", p: "Strategy also says what you won't do. That's often the hardest part — and the most valuable." },
      ],
      closer: ["You don't feel a good strategy in the plan.", "You feel it in everything that comes after."],
      cta: "Talk about your idea",
      meta: "Positioning, brand, marketing and digital strategy by Defy & Brand Events. Creativity without strategy becomes noise; strategy without creativity becomes boring. We bring both together.",
    },
    {
      slug: "brand-creative",
      num: "02",
      name: "Brand & Creative",
      role: "gives the idea its shape",
      headline: "Your brand deserves more than “good enough”.",
      intro: [
        "There are plenty of brands that look good. There are few you'd recognise with your eyes half closed.",
        "A brand shouldn't just be beautiful. It should be recognisable. Evoke a feeling. Take a position. Mean something.",
        "Creativity without meaning is decoration. We don't make decoration.",
      ],
      blocksTitle: "What we build",
      blocks: [
        { h: "Brand identity", p: "Who you are, what you stand for and why anyone should feel it. The foundation under everything you make next." },
        { h: "Visual identity", p: "Logo, colour, typography, imagery, motion — one system that's recognisable everywhere. From your website to your email signature." },
        { h: "Creative direction", p: "The red thread. We make sure every image, campaign and page breathes the same brand, even when ten different people are working on it." },
        { h: "Concepts", p: "The idea before the execution. Big enough to carry a year of campaigns, sharp enough to fit in one sentence." },
        { h: "Campaigns", p: "Creative work that takes a position. Not everyone has to like it. The right people have to remember it." },
        { h: "Art direction", p: "Photography, film, illustration, motion — directed so the image says what the words don't have to." },
        { h: "Visual storytelling", p: "A brand tells a story even when it's silent. We make sure it's the right one." },
      ],
      closer: ["“Good enough” is forgotten before the page has loaded.", "We build brands that stick."],
      cta: "Let's build something",
      meta: "Brand identity, visual identity, creative direction and campaigns by Defy & Brand Events. Creativity without meaning is decoration — we don't make decoration.",
    },
    {
      slug: "copywriting",
      num: "03",
      name: "Copywriting",
      role: "gives it a voice",
      headline: "Words that move people.",
      intro: [
        "Information is free. Attention isn't. Good copy doesn't explain. It makes someone want to know what happens next.",
        "We don't write texts. We find the words that make an idea land.",
      ],
      listTitle: "What words do",
      list: [
        "Good words grab attention.",
        "Make clear in one line what a page needed.",
        "Build desire where there was indifference.",
        "Give a brand a voice you'd recognise without the logo.",
        "And move people to the action you intended.",
      ],
      blocksTitle: "What we write for",
      blocks: [
        { h: "Websites", p: "Headlines that stop, structure that leads, microcopy that reassures at the exact moment someone hesitates." },
        { h: "Campaigns", p: "One idea, one line, and the discipline not to add anything." },
        { h: "Branding", p: "Manifestos, taglines, the sentences your team will repeat without being asked." },
        { h: "Social media", p: "Short, distinctive and human. Written for a scrolling thumb, not a jury." },
        { h: "Storytelling", p: "The story behind the product — told so it sticks, not so it's long." },
        { h: "Tone of voice", p: "How does your brand sound when it's angry, happy, reassuring? We define it so everyone who writes, writes the same brand." },
        { h: "Messaging", p: "What you say first, what comes next, and what you never say. The hierarchy that sharpens every piece of communication." },
        { h: "Conversion copy", p: "The words on the button, in the email, on the last page. Small in size, large in effect." },
      ],
      closer: ["Every word on your site costs someone half a second.", "We make sure it's worth it."],
      cta: "Tell us what you want to say",
      meta: "Copywriting for websites, campaigns, branding and social by Defy & Brand Events. We don't write texts; we find the words that make an idea land.",
    },
    {
      slug: "website-design",
      num: "04",
      name: "Website Design",
      role: "builds the digital experience",
      headline: "Don't build a website. Build the moment they decide to stay.",
      sub: "We don't design pages. We design the experience between the first click and the next decision.",
      intro: [
        "Someone lands on your site. Three seconds later they know whether they're staying. Not because they read your copy. Because they felt something: this is good, this fits, I want to see more.",
        "That moment is what we design.",
      ],
      listTitle: "What a website has to do",
      list: [
        "A beautiful website is the minimum. A good website does something.",
        "It grabs attention before you've explained anything.",
        "It builds trust without asking for it.",
        "It makes people curious about the next scroll.",
        "It keeps them there.",
        "And at the right moment, it lets them choose.",
      ],
      blocksTitle: "How we build",
      blocks: [
        { h: "Experience, not pages", p: "We think in scenes, not sections. What does someone see first? What moves? What happens when they scroll, click, hesitate? Every transition is a chance to say something without words." },
        { h: "UX/UI that gets out of the way", p: "Good interface goes unnoticed. What you notice is that it was easy. We design paths, not obstacles — and test them until they run on their own." },
        { h: "Storytelling in the structure", p: "A website is a story with an order. We decide what lands when, so that by the end the visitor knows exactly who you are and why it matters." },
        { h: "Conversion without tricks", p: "No fake urgency, no dark patterns. Just the right question at the right moment, asked of someone who's already convinced." },
        { h: "Interaction & motion", p: "Movement isn't decoration. It's how a site lets you feel what it means. We use it where it gives direction — and leave it out where it distracts." },
        { h: "Responsive, always", p: "On a phone on the train it has to feel as strong as on a big screen in a boardroom. That's not an afterthought. That's the design." },
        { h: "Performance is a feeling too", p: "A site that makes you wait, loses. We build light and fast — because slowness is the first thing people feel and the last thing they forgive." },
        { h: "Brand experience", p: "Your website is where your brand gets to be most fully itself. We make sure every pixel is." },
      ],
      closer: ["A website is finished when it does something to the people who visit it.", "Until then, it's a file."],
      cta: "Build the moment",
      meta: "Website design, UX/UI and digital experience by Defy & Brand Events. Don't build a website. Build the moment they decide to stay.",
    },
    {
      slug: "marketing",
      num: "05",
      name: "Marketing",
      role: "brings the right people to it",
      headline: "Marketing is our DNA.",
      sub: "People don't remember ads. They remember how you made them feel.",
      intro: [
        "Nobody remembers your campaign. People remember what they felt during it — and that feeling decides later, in the store, on your site, in a conversation.",
        "To us, marketing isn't buying visibility. It's shaping perception and influencing behaviour. Deliberately, measurably, and with respect for the human on the other side.",
      ],
      blocksTitle: "How we see marketing",
      blocks: [
        { h: "Strategy first", p: "Who needs to feel something? What should they do next? Only when that's sharp do we start making. Otherwise we're making noise." },
        { h: "A target audience isn't a segment. It's a person.", p: "With a day, a context and a reason to ignore you. We look for the moment when they don't." },
        { h: "Campaigns that say one thing", p: "Strong campaigns aren't full. They're sharp. One idea, executed on every channel as if it belonged there." },
        { h: "Content that deserves to be seen", p: "Not because the algorithm pushes it. Because people want it. That's the difference between reach and attention." },
        { h: "Performance and data", p: "Every euro has a reason and a result. We measure what matters — not what looks good in a report — and adjust while it's running." },
        { h: "The whole customer journey", p: "From first impression to repeat purchase. Marketing doesn't stop at the click. It stops at the behaviour you wanted to see." },
        { h: "Growth that lasts", p: "Anyone can grow fast with enough budget. We build growth that's still standing when the campaign ends." },
      ],
      closer: ["Good marketing doesn't change what people see.", "It changes what they think when they see it."],
      cta: "Make your move",
      meta: "Marketing as the combination of strategy, creativity, content, performance and data. Defy & Brand Events shapes perception and behaviour — not just visibility.",
    },
    {
      slug: "seo",
      num: "06",
      name: "SEO",
      role: "makes you findable",
      headline: "Being found is one thing. Being found by the right person at the right moment is another.",
      intro: [
        "SEO isn't a list of keywords and a spot on Google. It's understanding what people search for, why they search for it and what they expect to find — and then being the best place to land.",
      ],
      blocksTitle: "How we approach SEO",
      blocks: [
        { h: "Search intent over keywords", p: "Behind every search is a person with a question. We start with the question, not the word." },
        { h: "Relevance", p: "Ranking for something you don't deliver costs you visitors and trust. We focus on the searches that genuinely fit you." },
        { h: "Content that is the answer", p: "No text for the sake of text. Pages that answer the question better than anyone — Google loves that, because people do." },
        { h: "Technical foundation", p: "Speed, structure, mobile, indexability. Invisible to the visitor, decisive for the result." },
        { h: "Authority", p: "You build credibility, you don't install it. We work on the signals that say: this brand knows what it's talking about." },
        { h: "Visibility that converts", p: "Traffic isn't a goal. We measure what those visitors do — and optimise for that." },
      ],
      closer: ["The best position on Google is the one where the visitor thinks: this is exactly what I was looking for."],
      cta: "Get found by the right people",
      meta: "SEO by Defy & Brand Events: search intent, relevance, content, technical foundation, authority and conversion. Found by the right person at the right moment.",
    },
    {
      slug: "geo",
      num: "07",
      name: "GEO",
      role: "makes you understandable to AI",
      headline: "If AI doesn't understand you, it can't recommend you.",
      intro: [
        "More and more people don't search anymore. They ask. ChatGPT, Gemini, Copilot, Perplexity. “Which agency fits my project?” “Which product does this best?” “Who can help me with this?”",
        "And the answer doesn't come from a list of ten blue links. It comes from an AI that decides which companies, products and solutions seem relevant — and names them.",
        "GEO (Generative Engine Optimization) is about that decision. It makes sure AI systems understand who you are, what you do and who you do it for — so you're in the running at all.",
      ],
      listTitle: "Why it matters",
      list: [
        "An AI reads your website differently than a person does. It looks for clarity, coherence and evidence.",
        "Vague promises and marketing language don't help it. Concrete, reliable, consistent information does.",
        "If you're unclear, you're not misunderstood. You're skipped.",
      ],
      blocksTitle: "How we work on GEO",
      blocks: [
        { h: "Clarity", p: "What you do, for whom, and why it's different — in language a machine and a human both understand on first read." },
        { h: "Structure", p: "Information built so an AI can read it, connect it and cite it correctly. From page architecture to structured data." },
        { h: "Consistency", p: "The same facts on your site, in your profiles and in what others write about you. To an AI, contradictions are a reason to doubt." },
        { h: "Reliability", p: "Sources, numbers, cases, context. The more an AI can verify, the sooner it takes you seriously." },
        { h: "Relevance", p: "Matching the questions your customers actually ask — not the terms you use internally." },
      ],
      product: {
        h: "ceeme — our own GEO product",
        p: "With ceeme we measure how AI systems understand and mention your brand today, and what you can improve. Built by DB Events, used on this very site.",
        cta: "Discover ceeme",
        url: "https://www.ceeme.be",
      },
      honest: {
        h: "Honest about what GEO is",
        p: "GEO doesn't guarantee an AI will recommend you. Nobody can promise that — those systems make their own decisions. What GEO does do: make sure you're understood. And what's understood can be chosen.",
      },
      closer: ["What's understood can be chosen."],
      cta: "Let AI understand you",
      meta: "GEO (Generative Engine Optimization) by Defy & Brand Events: clear, structured, reliable information so AI systems like ChatGPT, Gemini and Perplexity understand you. No false guarantees.",
    },
    {
      slug: "agent-ready",
      num: "08",
      name: "Agent Ready",
      role: "makes you ready for AI agents",
      headline: "Understandable to people. Readable by machines.",
      intro: [
        "Until now, people visited your website. Soon AI agents will too — and increasingly on their behalf.",
        "An agent is software that's given a task and carries it out on its own: finding information, comparing providers, interpreting prices, booking an appointment, requesting a quote. Without a human watching every screen.",
        "If that agent doesn't understand your website, it moves on to the next one.",
      ],
      blocksTitle: "What Agent Ready means",
      blocks: [
        { h: "Clear information", p: "What you offer, what it costs, where you operate, how to reach you — without anyone having to infer it from a mood shot." },
        { h: "Structured content", p: "Information in a form machines recognise: consistent, labelled, in a logical place. Invisible to a person. To an agent, the difference between understanding and guessing." },
        { h: "Reliable business data", p: "Opening hours, addresses, contact details, products — one version of the truth, the same everywhere." },
        { h: "Digital accessibility", p: "What's accessible to people with disabilities is usually readable by machines too. Same principles: clarity, structure, no surprises." },
        { h: "Machine-readable content", p: "Your site speaks two languages at once: your customer's, and that of the systems your customer uses." },
        { h: "AI discoverability", p: "Being found, understood and represented correctly in the tools where your customers increasingly start." },
      ],
      closer: ["Agent Ready means making sure your business also exists in the place where decisions increasingly begin: a conversation between a person and a machine."],
      cta: "Check if you're ready",
      meta: "Agent Ready by Defy & Brand Events: clear, structured, reliable business information so AI agents understand your website and represent it correctly.",
    },
    {
      slug: "agentic-workflow",
      num: "09",
      name: "Agentic Workflow",
      role: "lets technology act",
      headline: "From using AI to putting AI to work.",
      intro: [
        "Most companies use AI to write faster or generate ideas. Useful. But it's a first step.",
        "The next step is AI that does something. That supports a process, prepares a decision, carries out an action — and learns from it. We call that an agentic workflow.",
      ],
      steps: [
        { k: "Trigger", p: "Something happens: a request comes in, a customer hesitates, stock drops, a day begins." },
        { k: "Think", p: "The agent gathers what it needs — context, data, rules — and understands the situation." },
        { k: "Decide", p: "It chooses the best next step. On its own where it can, with a human where it should." },
        { k: "Act", p: "It executes: an email, an update in your system, a quote, a schedule, an alert." },
        { k: "Measure", p: "What happened next? Did it work? How fast, how well?" },
        { k: "Improve", p: "Next time it does better. Not because someone told it to, but because it saw." },
      ],
      blocksTitle: "Where it makes sense",
      blocks: [
        { h: "Lead follow-up", p: "That never leaves anything for tomorrow." },
        { h: "Content", p: "That's ready at the right moment." },
        { h: "Customer questions", p: "That get a good answer at 3 a.m." },
        { h: "Reports", p: "That write themselves and come with a recommendation." },
        { h: "Processes", p: "That no longer wait for whoever happens to know the password." },
      ],
      honest: {
        h: "Our rule",
        p: "Technology is only interesting when it makes work better, faster or smarter. Otherwise it's a demo. We don't build AI to have AI. We find the place in your business where an intelligent workflow removes time, errors or frustration — and build exactly that.",
      },
      closer: ["Technology is only interesting when it makes work better, faster or smarter.", "Otherwise it's a demo."],
      cta: "Put technology to work",
      meta: "Agentic workflows, AI agents and automation by Defy & Brand Events. Trigger. Think. Decide. Act. Measure. Improve. From using AI to putting AI to work.",
    },
  ],
};
