import type { Copy } from "./types";

export const fr: Copy = {
  lang: "fr",
  nav: { work: "Portfolio", services: "Services", about: "Qui & pourquoi", contact: "Contact" },
  routes: { services: "services", about: "a-propos", contact: "contact", portfolio: "portfolio" },
  portfolio: { eyebrow: "Ce qu'on a déjà créé", h: "Chaque projet ici est né d'une seule idée : ça doit rester.", hint: "Survolez un nom. Cliquez pour ouvrir le site.", live: "En ligne", wip: "En cours", visit: "Ouvrir le site", meta: "Sites et campagnes signés Defy & Brand Events : Rhumerie Louis, AI in de klas, DPODR, EcoClean Luxembourg, Karweiservice Vanden Berghe, Oostende.ai, Customm." },
  meta: {
    title: "Defy & Brand Events — We turn ideas into experiences",
    description:
      "Defy & Brand Events transforme les idées en marques, sites, campagnes et expériences prêtes pour l'IA qui touchent et font bouger les gens. Stratégie, créativité et technologie dans une seule équipe.",
  },
  home: {
    heroLead: "WE TURN IDEAS INTO EXPERIENCES.",
    heroIntro:
      "Une idée n'est rien tant que personne ne la ressent. Nous créons des marques, des sites, des campagnes et des mots qui fabriquent ce moment-là : celui où quelqu'un s'arrête, regarde, comprend — et choisit.",
    heroCta: "Montrez-nous ce que vous avez en tête",
    statement: [
      "Pas une agence avec un menu.",
      "Une équipe qui pense, crée, teste et améliore — jusqu'à ce que l'idée fasse ce qu'elle devait faire.",
    ],
    manifesto: "Une idée n'est rien tant que personne ne la ressent.",
    manifestoAfter: "WE TURN IDEAS INTO EXPERIENCES.",
    servicesEyebrow: "Neuf services. Un seul mouvement.",
    servicesHint: "Scrollez pour tourner",
    chainEyebrow: "De l'idée à l'action",
    chain: [
      { h: "An idea", p: "Strategy donne la direction. Brand & Creative donne forme à l'idée." },
      { h: "becomes a brand", p: "Copywriting lui donne une voix. Website Design construit l'expérience digitale." },
      { h: "becomes an experience", p: "Marketing y amène les bonnes personnes. SEO vous rend trouvable, GEO vous rend compréhensible pour l'IA." },
      { h: "becomes action", p: "Agent Ready vous prépare aux agents IA. Agentic Workflow fait réellement agir la technologie." },
    ],
    chainNote: "C'est ça que nous appelons Events. Pas une salle et une scène. Le moment où tout se rejoint et où quelqu'un se met en mouvement.",
    closerH: "Vous avez une idée. Nous en faisons quelque chose que les gens ressentent.",
    closerCta: "Let's make it happen",
  },
  about: {
    eyebrow: "Qui nous sommes, et pourquoi",
    h: "We don't build brands. We build the moment someone cares.",
    why: [
      "Nous avons vu trop de bonnes idées mourir.",
      "Dans une présentation que personne n'a rouverte. Dans une stratégie sans personne pour l'exécuter. Dans une campagne « créative » et rien d'autre. Dans un site magnifique qui ne faisait rien.",
      "Defy & Brand est né de l'impatience face à ce schéma.",
    ],
    notTitle: "Ce que nous ne faisons pas",
    not: [
      "Pas de one-size-fits-all. Votre marque n'a pas besoin d'un template, elle a besoin d'une réponse.",
      "Pas d'idées qui disparaissent dans un tiroir. Si nous le pensons, nous le construisons.",
      "Pas de stratégie sans exécution. Un plan qu'on ne construit pas, c'est une opinion.",
      "Pas de créativité pour être créatif. Si ça ne veut rien dire, ça ne fait rien.",
    ],
    howTitle: "Notre façon de travailler",
    verbs: ["Nous pensons.", "Nous créons.", "Nous testons.", "Nous améliorons.", "Nous donnons vie aux idées."],
    howNote: "Dans cet ordre, puis on recommence. Petite équipe, circuits courts, pas d'intermédiaires. Vous parlez aux gens qui font le travail.",
    nameTitle: "Ce que dit notre nom",
    name: [
      { k: "Defy", p: "c'est refuser de faire ce que tout votre secteur fait, simplement parce que tout le monde le fait." },
      { k: "Brand", p: "c'est la discipline qui donne une direction à cette audace." },
      { k: "Events", p: "c'est ce qui se passe quand ça marche : une expérience qui touche quelqu'un et le met en mouvement." },
    ],
    cta: "Faisons connaissance",
    meta: "Pourquoi Defy & Brand Events existe : pas de one-size-fits-all, pas de stratégie sans exécution. Nous pensons, créons, testons, améliorons et donnons vie aux idées.",
  },
  contact: {
    h: "Vous avez quelque chose en tête. On en fait quoi ?",
    lines: [
      "Une idée qui n'a pas encore de forme.",
      "Un problème que vous regardez depuis trop longtemps.",
      "Une ambition plus grande que votre site actuel.",
      "Un projet qui doit aller quelque part — et ne sait pas encore où.",
    ],
    invite: "Vous n'avez pas besoin que ce soit prêt. Vous avez juste besoin de le raconter.",
    talk: "Let's make some noise.",
    labels: {
      who: "Qui êtes-vous ?",
      reach: "Comment vous joindre ?",
      what: "Racontez. (En vrac, c'est parfait. En vrac, c'est souvent mieux.)",
      send: "Envoyer",
    },
    confirm: "Bien reçu. Nous le lisons vraiment, et un humain vous répond sous deux jours ouvrables — pas un répondeur automatique.",
    alt: "Vous préférez parler tout de suite ?",
    meta: "Une idée, un problème, une ambition ? Racontez-le à Defy & Brand Events. Pas besoin que ce soit prêt.",
    cine: {
      eyebrow: "La créative derrière les idées",
      name: "ThinkRebel",
      role: "Njusja Orban — Creative",
      quote: "Certaines idées ont besoin d’une stratégie. D’autres, juste de quelqu’un d’assez fou pour les réaliser.",
      have: "Une idée ?",
      make: "Let's make it happen.",
      tell: "Dites-nous ce que vous avez en tête. On trouvera quoi en faire.",
      cta: "Let's make some noise",
    },
  },
  footer: { tagline: "We turn ideas into experiences.", another: "Une autre idée ? Let's make some noise." },
  services: [
    {
      slug: "strategy",
      num: "01",
      name: "Strategy",
      role: "donne la direction",
      headline: "STRATEGY MEETS CREATIVITY. THAT'S WHERE THE MAGIC HAPPENS.",
      intro: [
        "La créativité sans stratégie devient du bruit. La stratégie sans créativité devient ennuyeuse.",
        "Nous ne choisissons pas entre les deux. Nous les réunissons — et c'est là que ça se passe.",
      ],
      blocksTitle: "De quoi parle la stratégie",
      blocks: [
        { h: "Positionnement", p: "Qu'êtes-vous que personne d'autre n'est ? Et osez-vous le dire ? Nous cherchons la place encore libre dans la tête de votre client — et nous la prenons." },
        { h: "Stratégie de marque", p: "Pourquoi vous existez, ce que vous promettez et comment vous le tenez avec constance. La base sur laquelle chaque idée créative est mise à l'épreuve." },
        { h: "Stratégie marketing", p: "Qui, quand, où, avec quel message. Pas tout pour tout le monde. La bonne chose pour les bonnes personnes." },
        { h: "Stratégie digitale", p: "Quel rôle jouent votre site, votre contenu, vos données, l'IA ? Pas « parce qu'il faut », mais parce que ça apporte quelque chose à votre client." },
        { h: "Cible et parcours client", p: "Comment quelqu'un décide-t-il vraiment ? Où hésite-t-il, où décroche-t-il, où le convainquez-vous ? Nous traçons le chemin et construisons sur les points qui font la différence." },
        { h: "Direction et croissance", p: "La stratégie dit aussi ce que vous ne ferez pas. C'est souvent le plus difficile — et le plus précieux." },
      ],
      closer: ["Une bonne stratégie ne se sent pas dans le plan.", "Elle se sent dans tout ce qui vient après."],
      cta: "Parlons de votre idée",
      meta: "Positionnement, stratégie de marque, marketing et digitale par Defy & Brand Events. La créativité sans stratégie devient du bruit ; la stratégie sans créativité devient ennuyeuse. Nous réunissons les deux.",
    },
    {
      slug: "brand-creative",
      num: "02",
      name: "Brand & Creative",
      role: "donne forme à l'idée",
      headline: "YOUR BRAND DESERVES MORE THAN “GOOD ENOUGH”.",
      intro: [
        "Il y a beaucoup de marques qui ont belle allure. Il y en a peu qu'on reconnaît les yeux mi-clos.",
        "Une marque ne doit pas seulement être belle. Elle doit être reconnaissable. Évoquer un sentiment. Prendre position. Vouloir dire quelque chose.",
        "La créativité sans sens, c'est de la décoration. Nous ne faisons pas de décoration.",
      ],
      blocksTitle: "Ce que nous construisons",
      blocks: [
        { h: "Brand identity", p: "Qui vous êtes, ce que vous défendez et pourquoi quelqu'un devrait le ressentir. Le socle de tout ce que vous créerez ensuite." },
        { h: "Visual identity", p: "Logo, couleur, typographie, image, mouvement — un seul système, reconnaissable partout. De votre site à votre signature d'e-mail." },
        { h: "Creative direction", p: "Le fil rouge. Nous veillons à ce que chaque image, chaque campagne et chaque page respirent la même marque, même quand dix personnes différentes y travaillent." },
        { h: "Concepts", p: "L'idée avant l'exécution. Assez grande pour porter un an de campagnes, assez nette pour tenir en une phrase." },
        { h: "Campagnes", p: "Un travail créatif qui prend position. Tout le monde n'a pas à l'aimer. Les bonnes personnes doivent s'en souvenir." },
        { h: "Art direction", p: "Photo, film, illustration, motion — dirigés pour que l'image dise ce que les mots n'ont pas besoin de dire." },
        { h: "Visual storytelling", p: "Une marque raconte une histoire même quand elle se tait. Nous veillons à ce que ce soit la bonne." },
      ],
      closer: ["Le « suffisamment bien » est oublié avant que la page ait fini de charger.", "Nous construisons des marques qui restent."],
      cta: "Construisons quelque chose",
      meta: "Brand identity, identité visuelle, direction créative et campagnes par Defy & Brand Events. La créativité sans sens, c'est de la décoration — nous n'en faisons pas.",
    },
    {
      slug: "copywriting",
      num: "03",
      name: "Copywriting",
      role: "lui donne une voix",
      headline: "WORDS THAT MOVE PEOPLE.",
      intro: [
        "L'information est gratuite. L'attention ne l'est pas. Un bon texte n'explique pas. Il donne envie de savoir ce qui vient après.",
        "Nous n'écrivons pas des textes. Nous trouvons les mots qui font atterrir une idée.",
      ],
      listTitle: "Ce que font les mots",
      list: [
        "Les bons mots captent l'attention.",
        "Rendent clair en une phrase ce qu'une page attendait.",
        "Créent le désir là où il y avait de l'indifférence.",
        "Donnent à une marque une voix reconnaissable sans logo.",
        "Et poussent les gens vers l'action que vous visiez.",
      ],
      blocksTitle: "Ce pour quoi nous écrivons",
      blocks: [
        { h: "Sites web", p: "Des titres qui arrêtent, une structure qui guide, une microcopy qui rassure au moment précis où quelqu'un hésite." },
        { h: "Campagnes", p: "Une idée, une phrase, et la discipline de ne rien ajouter." },
        { h: "Branding", p: "Manifestes, signatures, les phrases que votre équipe répétera sans qu'on le lui demande." },
        { h: "Réseaux sociaux", p: "Court, singulier, humain. Écrit pour un pouce qui scrolle, pas pour un jury." },
        { h: "Storytelling", p: "L'histoire derrière le produit — racontée pour qu'elle reste, pas pour qu'elle soit longue." },
        { h: "Tone of voice", p: "Comment sonne votre marque quand elle est fâchée, joyeuse, rassurante ? Nous le fixons pour que tous ceux qui écrivent, écrivent la même marque." },
        { h: "Messaging", p: "Ce que vous dites d'abord, ensuite, et ce que vous ne dites jamais. La hiérarchie qui affûte chaque communication." },
        { h: "Conversion copy", p: "Les mots sur le bouton, dans l'e-mail, sur la dernière page. Petits par la taille, grands par l'effet." },
      ],
      closer: ["Chaque mot de votre site coûte une demi-seconde à quelqu'un.", "Nous faisons en sorte qu'il la vaille."],
      cta: "Dites-nous ce que vous voulez dire",
      meta: "Copywriting pour sites, campagnes, branding et réseaux sociaux par Defy & Brand Events. Nous n'écrivons pas des textes ; nous trouvons les mots qui font atterrir une idée.",
    },
    {
      slug: "website-design",
      num: "04",
      name: "Website Design",
      role: "construit l'expérience digitale",
      headline: "DON'T BUILD A WEBSITE. BUILD THE MOMENT THEY DECIDE TO STAY.",
      sub: "We don't design pages. We design the experience between the first click and the next decision.",
      intro: [
        "Quelqu'un arrive sur votre site. Trois secondes plus tard, il sait s'il reste. Pas parce qu'il a lu vos textes. Parce qu'il a ressenti quelque chose : c'est bien, c'est juste, je veux voir la suite.",
        "Ce moment-là, c'est ce que nous concevons.",
      ],
      listTitle: "Ce qu'un site doit faire",
      list: [
        "Un beau site, c'est le minimum. Un bon site fait quelque chose.",
        "Il capte l'attention avant d'avoir expliqué quoi que ce soit.",
        "Il installe la confiance sans la demander.",
        "Il donne envie de scroller plus loin.",
        "Il fait rester.",
        "Et au bon moment, il fait choisir.",
      ],
      blocksTitle: "Notre façon de construire",
      blocks: [
        { h: "Une expérience, pas des pages", p: "Nous pensons en scènes, pas en sections. Que voit-on d'abord ? Qu'est-ce qui bouge ? Que se passe-t-il quand on scrolle, clique, hésite ? Chaque transition est une occasion de dire quelque chose sans mots." },
        { h: "Un UX/UI qui s'efface", p: "Une bonne interface ne se remarque pas. Ce qu'on remarque, c'est que c'était simple. Nous dessinons des chemins, pas des obstacles — et nous les testons jusqu'à ce qu'ils coulent de source." },
        { h: "Le récit dans la structure", p: "Un site est une histoire avec un ordre. Nous décidons ce qui atterrit quand, pour qu'à la fin le visiteur sache exactement qui vous êtes et pourquoi ça compte." },
        { h: "La conversion sans artifices", p: "Pas de fausse urgence, pas de dark patterns. Juste la bonne question au bon moment, posée à quelqu'un de déjà convaincu." },
        { h: "Interaction & motion", p: "Le mouvement n'est pas un ornement. C'est la manière dont un site fait sentir ce qu'il veut dire. Nous l'utilisons là où il guide — et nous l'enlevons là où il distrait." },
        { h: "Responsive, toujours", p: "Sur un téléphone dans le train, ça doit être aussi fort que sur un grand écran en salle de réunion. Ce n'est pas une adaptation après coup. C'est le design." },
        { h: "La performance est aussi une sensation", p: "Un site qui fait attendre perd. Nous construisons léger et rapide — parce que la lenteur est la première chose qu'on ressent et la dernière qu'on pardonne." },
        { h: "Brand experience", p: "Votre site est l'endroit où votre marque a le droit d'être pleinement elle-même. Nous veillons à ce que chaque pixel le soit." },
      ],
      closer: ["Un site est terminé quand il fait quelque chose aux gens qui le visitent.", "Avant ça, c'est un fichier."],
      cta: "Construisons ce moment",
      meta: "Website design, UX/UI et expérience digitale par Defy & Brand Events. Don't build a website. Build the moment they decide to stay.",
    },
    {
      slug: "marketing",
      num: "05",
      name: "Marketing",
      role: "y amène les bonnes personnes",
      headline: "MARKETING IS OUR DNA.",
      sub: "People don't remember ads. They remember how you made them feel.",
      intro: [
        "Personne ne se souvient de votre campagne. Les gens se souviennent de ce qu'ils ont ressenti — et c'est ce sentiment qui décide plus tard, en magasin, sur votre site, dans une conversation.",
        "Pour nous, le marketing n'est pas de la visibilité qu'on achète. C'est une perception qu'on façonne et un comportement qu'on influence. Délibérément, mesurablement, et avec respect pour l'humain en face.",
      ],
      blocksTitle: "Notre vision du marketing",
      blocks: [
        { h: "La stratégie d'abord", p: "Qui doit ressentir quelque chose ? Que doit-il faire ensuite ? C'est seulement quand c'est net que nous commençons à créer. Sinon, nous produisons du bruit." },
        { h: "Une cible n'est pas un segment. C'est une personne.", p: "Avec une journée, un contexte et une bonne raison de vous ignorer. Nous cherchons le moment où elle ne le fait pas." },
        { h: "Des campagnes qui disent une seule chose", p: "Les campagnes fortes ne sont pas pleines. Elles sont nettes. Une idée, déclinée sur chaque canal comme si elle y était née." },
        { h: "Du contenu qui mérite d'être vu", p: "Pas parce que l'algorithme le pousse. Parce que les gens le veulent. C'est la différence entre la portée et l'attention." },
        { h: "Performance et données", p: "Chaque euro a une raison et un résultat. Nous mesurons ce qui compte — pas ce qui fait joli dans un rapport — et nous ajustons en cours de route." },
        { h: "Tout le parcours client", p: "De la première impression au réachat. Le marketing ne s'arrête pas au clic. Il s'arrête au comportement que vous vouliez voir." },
        { h: "Une croissance qui tient", p: "Croître vite, tout le monde y arrive avec assez de budget. Nous construisons une croissance qui tient encore debout quand la campagne s'arrête." },
      ],
      closer: ["Le bon marketing ne change pas ce que les gens voient.", "Il change ce qu'ils pensent en le voyant."],
      cta: "Passez à l'action",
      meta: "Le marketing comme combinaison de stratégie, créativité, contenu, performance et données. Defy & Brand Events façonne la perception et le comportement — pas seulement la visibilité.",
    },
    {
      slug: "seo",
      num: "06",
      name: "SEO",
      role: "vous rend trouvable",
      headline: "Être trouvé, c'est une chose. Être trouvé par la bonne personne au bon moment, c'en est une autre.",
      intro: [
        "Le SEO n'est pas une liste de mots-clés et une place sur Google. C'est comprendre ce que les gens cherchent, pourquoi ils le cherchent et ce qu'ils s'attendent à trouver — puis être le meilleur endroit où atterrir.",
      ],
      blocksTitle: "Notre approche du SEO",
      blocks: [
        { h: "L'intention avant le mot-clé", p: "Derrière chaque recherche, il y a une personne avec une question. Nous partons de la question, pas du mot." },
        { h: "La pertinence", p: "Être classé sur quelque chose que vous ne livrez pas vous coûte des visiteurs et de la confiance. Nous visons les recherches qui vous correspondent vraiment." },
        { h: "Un contenu qui est la réponse", p: "Pas de texte pour faire du texte. Des pages qui répondent à la question mieux que quiconque — Google aime ça, parce que les gens aiment ça." },
        { h: "Une base technique solide", p: "Vitesse, structure, mobile, indexabilité. Invisible pour le visiteur, décisif pour le résultat." },
        { h: "L'autorité", p: "La crédibilité se construit, elle ne s'installe pas. Nous travaillons les signaux qui disent : cette marque sait de quoi elle parle." },
        { h: "Une visibilité qui convertit", p: "Le trafic n'est pas un objectif. Nous mesurons ce que ces visiteurs font — et nous optimisons pour ça." },
      ],
      closer: ["La meilleure position sur Google, c'est celle où le visiteur pense : c'est exactement ce que je cherchais."],
      cta: "Faites-vous trouver par les bonnes personnes",
      meta: "SEO par Defy & Brand Events : intention de recherche, pertinence, contenu, base technique, autorité et conversion. Être trouvé par la bonne personne au bon moment.",
    },
    {
      slug: "geo",
      num: "07",
      name: "GEO",
      role: "vous rend compréhensible pour l'IA",
      headline: "IF AI DOESN'T UNDERSTAND YOU, IT CAN'T RECOMMEND YOU.",
      intro: [
        "De plus en plus de gens ne cherchent plus. Ils demandent. À ChatGPT, Gemini, Copilot, Perplexity. « Quelle agence correspond à mon projet ? » « Quel produit fait ça le mieux ? » « Qui peut m'aider avec ça ? »",
        "Et la réponse ne vient pas d'une liste de dix liens bleus. Elle vient d'une IA qui décide quelles entreprises, quels produits et quelles solutions semblent pertinents — et qui les nomme.",
        "Le GEO (Generative Engine Optimization) porte sur cette décision. Il fait en sorte que les systèmes d'IA comprennent qui vous êtes, ce que vous faites et pour qui — pour que vous soyez seulement dans la course.",
      ],
      listTitle: "Pourquoi ça compte",
      list: [
        "Une IA lit votre site autrement qu'un humain. Elle cherche de la clarté, de la cohérence et des preuves.",
        "Les promesses vagues et le jargon marketing ne l'aident pas. Une information concrète, fiable et constante, oui.",
        "Quand on est flou, on n'est pas mal compris. On est ignoré.",
      ],
      blocksTitle: "Notre travail en GEO",
      blocks: [
        { h: "Clarté", p: "Ce que vous faites, pour qui, et en quoi c'est différent — dans un langage qu'une machine et un humain comprennent du premier coup." },
        { h: "Structure", p: "Une information construite pour qu'une IA puisse la lire, la relier et la citer correctement. De l'architecture des pages aux données structurées." },
        { h: "Cohérence", p: "Les mêmes faits sur votre site, dans vos profils et dans ce que d'autres écrivent sur vous. Pour une IA, une contradiction est une raison de douter." },
        { h: "Fiabilité", p: "Sources, chiffres, cas, contexte. Plus une IA peut vérifier, plus vite elle vous prend au sérieux." },
        { h: "Pertinence", p: "Coller aux questions que vos clients posent vraiment — pas aux termes que vous utilisez en interne." },
      ],
      product: {
        h: "ceeme — notre propre produit GEO",
        p: "Avec ceeme, nous mesurons comment les systèmes d’IA comprennent et citent votre marque aujourd’hui, et ce que vous pouvez améliorer. Conçu par DB Events, utilisé sur ce site.",
        cta: "Découvrir ceeme",
        url: "https://www.ceeme.be",
      },
      honest: {
        h: "Le GEO, en toute honnêteté",
        p: "Le GEO ne garantit pas qu'une IA vous recommandera. Personne ne peut le promettre — ces systèmes décident seuls. Ce que le GEO fait : s'assurer que vous êtes compris. Et ce qui est compris peut être choisi.",
      },
      closer: ["Ce qui est compris peut être choisi."],
      cta: "Faites-vous comprendre par l'IA",
      meta: "GEO (Generative Engine Optimization) par Defy & Brand Events : une information claire, structurée et fiable pour que les systèmes d'IA comme ChatGPT, Gemini et Perplexity vous comprennent. Sans fausses garanties.",
    },
    {
      slug: "agent-ready",
      num: "08",
      name: "Agent Ready",
      role: "vous prépare aux agents IA",
      headline: "Compréhensible pour les humains. Lisible par les machines.",
      intro: [
        "Jusqu'ici, des personnes visitaient votre site. Bientôt, des agents IA le feront aussi — et de plus en plus à leur place.",
        "Un agent, c'est un logiciel qui reçoit une mission et l'exécute seul : chercher une information, comparer des prestataires, interpréter des prix, fixer un rendez-vous, demander un devis. Sans qu'un humain regarde chaque écran.",
        "Si cet agent ne comprend pas votre site, il passe au suivant.",
      ],
      blocksTitle: "Ce que signifie Agent Ready",
      blocks: [
        { h: "Une information claire", p: "Ce que vous proposez, ce que ça coûte, où vous êtes actif, comment vous joindre — sans qu'on doive le déduire d'une photo d'ambiance." },
        { h: "Un contenu structuré", p: "L'information dans une forme que les machines reconnaissent : cohérente, étiquetée, au bon endroit. Invisible pour un humain. Pour un agent, la différence entre comprendre et deviner." },
        { h: "Des données d'entreprise fiables", p: "Horaires, adresses, coordonnées, produits — une seule version de la vérité, identique partout." },
        { h: "L'accessibilité numérique", p: "Ce qui est accessible aux personnes en situation de handicap est généralement lisible par les machines aussi. Mêmes principes : clarté, structure, pas de surprises." },
        { h: "Un contenu machine-readable", p: "Votre site parle deux langues à la fois : celle de votre client et celle des systèmes que votre client utilise." },
        { h: "AI discoverability", p: "Être trouvé, compris et représenté correctement dans les outils par lesquels vos clients commencent de plus en plus souvent." },
      ],
      closer: ["Agent Ready, c'est faire en sorte que votre entreprise existe aussi là où les décisions commencent de plus en plus : dans une conversation entre un humain et une machine."],
      cta: "Vérifiez si vous êtes prêt",
      meta: "Agent Ready par Defy & Brand Events : une information d'entreprise claire, structurée et fiable pour que les agents IA comprennent votre site et le représentent correctement.",
    },
    {
      slug: "agentic-workflow",
      num: "09",
      name: "Agentic Workflow",
      role: "fait agir la technologie",
      headline: "D'utiliser l'IA à faire travailler l'IA.",
      intro: [
        "La plupart des entreprises utilisent l'IA pour écrire plus vite ou générer des idées. Utile. Mais c'est un premier pas.",
        "Le pas suivant, c'est une IA qui fait quelque chose. Qui soutient un processus, prépare une décision, exécute une action — et en tire des leçons. C'est ce que nous appelons un agentic workflow.",
      ],
      steps: [
        { k: "Trigger", p: "Quelque chose se produit : une demande arrive, un client hésite, un stock baisse, une journée commence." },
        { k: "Think", p: "L'agent rassemble ce dont il a besoin — contexte, données, règles — et comprend la situation." },
        { k: "Decide", p: "Il choisit la meilleure étape suivante. Seul quand c'est possible, avec un humain quand c'est nécessaire." },
        { k: "Act", p: "Il exécute : un e-mail, une mise à jour dans votre système, un devis, un planning, une alerte." },
        { k: "Measure", p: "Que s'est-il passé ensuite ? Ça a fonctionné ? À quelle vitesse, avec quelle qualité ?" },
        { k: "Improve", p: "La fois suivante, il fait mieux. Pas parce qu'on le lui a dit, mais parce qu'il l'a vu." },
      ],
      blocksTitle: "Là où ça a du sens",
      blocks: [
        { h: "Suivi de leads", p: "Qui ne laisse jamais rien traîner." },
        { h: "Contenu", p: "Prêt au bon moment." },
        { h: "Questions clients", p: "Qui reçoivent une bonne réponse à trois heures du matin." },
        { h: "Rapports", p: "Qui s'écrivent seuls et arrivent avec une recommandation." },
        { h: "Processus", p: "Qui n'attendent plus la personne qui connaît le mot de passe." },
      ],
      honest: {
        h: "Notre règle",
        p: "La technologie n'est intéressante que si elle rend le travail meilleur, plus rapide ou plus intelligent. Sinon, c'est une démo. Nous ne construisons pas de l'IA pour avoir de l'IA. Nous cherchons l'endroit de votre entreprise où un workflow intelligent supprime du temps, des erreurs ou de la frustration — et nous construisons exactement ça.",
      },
      closer: ["La technologie n'est intéressante que si elle rend le travail meilleur, plus rapide ou plus intelligent.", "Sinon, c'est une démo."],
      cta: "Faites travailler la technologie",
      meta: "Agentic workflows, agents IA et automatisation par Defy & Brand Events. Trigger. Think. Decide. Act. Measure. Improve. D'utiliser l'IA à faire travailler l'IA.",
    },
  ],
};
