import type { Copy } from "./types";

export const nl: Copy = {
  lang: "nl",
  nav: { work: "Werk", services: "Diensten", about: "Over", contact: "Contact" },
  routes: { services: "diensten", about: "over", contact: "contact" },
  meta: {
    title: "Defy & Brand Events — We turn ideas into experiences",
    description:
      "Defy & Brand Events zet ideeën om in merken, websites, campagnes en AI-klare ervaringen die mensen raken en in beweging brengen. Strategie, creativiteit en technologie in één team.",
  },
  home: {
    heroLead: "WE TURN IDEAS INTO EXPERIENCES.",
    heroIntro:
      "Een idee is niets tot iemand het voelt. Wij bouwen merken, websites, campagnes en woorden die dat moment maken: het moment waarop iemand stopt, kijkt, begrijpt — en kiest.",
    heroCta: "Laat zien wat je denkt",
    statement: [
      "Geen bureau met een menu.",
      "Eén team dat denkt, maakt, test en verbetert — tot het idee doet wat het moest doen.",
    ],
    manifesto: "Een idee is niets tot iemand het voelt.",
    manifestoAfter: "WE TURN IDEAS INTO EXPERIENCES.",
    servicesEyebrow: "Negen diensten. Één beweging.",
    servicesHint: "Scroll om te draaien",
    chainEyebrow: "Van idee naar actie",
    chain: [
      { h: "An idea", p: "Strategy bepaalt de richting. Brand & Creative geeft het idee vorm." },
      { h: "becomes a brand", p: "Copywriting geeft het een stem. Website Design bouwt de digitale ervaring." },
      { h: "becomes an experience", p: "Marketing brengt de juiste mensen ernaartoe. SEO maakt je vindbaar, GEO maakt je begrijpelijk voor AI." },
      { h: "becomes action", p: "Agent Ready maakt je klaar voor AI agents. Agentic Workflow laat technologie daadwerkelijk handelen." },
    ],
    chainNote:
      "Dat is wat wij bedoelen met Events. Niet een zaal en een podium. Het moment waarop alles samenkomt en iemand in beweging komt.",
    closerH: "Je hebt een idee. Wij maken er iets van dat mensen voelen.",
    closerCta: "Let's make it happen",
  },
  about: {
    eyebrow: "Waarom wij bestaan",
    h: "We don't build brands. We build the moment someone cares.",
    why: [
      "Wij hebben te veel goede ideeën zien sterven.",
      "In een presentatie die niemand meer opende. In een strategie zonder iemand die ze uitvoerde. In een campagne die “creatief” was en verder niets. In een website die er prachtig uitzag en niets deed.",
      "Defy & Brand is opgericht uit ongeduld met dat patroon.",
    ],
    notTitle: "Waar wij niet aan doen",
    not: [
      "Geen one-size-fits-all. Jouw merk heeft geen template nodig, het heeft een antwoord nodig.",
      "Geen ideeën die in een lade verdwijnen. Als we het bedenken, maken we het ook.",
      "Geen strategie zonder uitvoering. Een plan dat niet gebouwd wordt, is een mening.",
      "Geen creativiteit om creatief te zijn. Als het niets betekent, doet het niets.",
    ],
    howTitle: "Hoe wij werken",
    verbs: ["We denken.", "We maken.", "We testen.", "We verbeteren.", "We brengen ideeën tot leven."],
    howNote:
      "In die volgorde, en dan opnieuw. Klein team, korte lijnen, geen tussenlagen. Je spreekt met de mensen die het werk doen.",
    nameTitle: "Defy & Brand — de naam",
    name: [
      { k: "Defy", p: "is de weigering om te doen wat iedereen in je sector doet, alleen omdat iedereen het doet." },
      { k: "Brand", p: "is de discipline om die durf richting te geven." },
      { k: "Events", p: "is wat er gebeurt als het lukt: een ervaring die iemand raakt en in beweging brengt." },
    ],
    cta: "Leer ons kennen",
    meta: "Waarom Defy & Brand Events bestaat: geen one-size-fits-all, geen strategie zonder uitvoering. We denken, maken, testen, verbeteren en brengen ideeën tot leven.",
  },
  contact: {
    h: "Je hebt iets in je hoofd. Laten we het eruit halen.",
    lines: [
      "Een idee dat nog geen vorm heeft.",
      "Een probleem waar je al te lang naar kijkt.",
      "Een ambitie die groter is dan je huidige website.",
      "Een project dat ergens naartoe moet — en nog niet weet waar.",
    ],
    invite: "Je hoeft het niet klaar te hebben. Je hoeft het alleen te vertellen.",
    talk: "Let's talk.",
    labels: {
      who: "Wie ben je?",
      reach: "Hoe bereiken we je?",
      what: "Waar denk je aan? (Ruw mag. Ruw is meestal het beste.)",
      send: "Stuur het",
    },
    confirm: "Aangekomen. We lezen het écht, en je hoort binnen twee werkdagen van een mens — niet van een autoresponder.",
    alt: "Liever meteen praten?",
    meta: "Een idee, een probleem, een ambitie? Vertel het aan Defy & Brand Events. Je hoeft het niet klaar te hebben.",
  },
  footer: { tagline: "We turn ideas into experiences.", another: "Nog een idee? Let's talk." },
  services: [
    {
      slug: "strategy",
      num: "01",
      name: "Strategy",
      role: "bepaalt de richting",
      headline: "STRATEGY MEETS CREATIVITY. THAT'S WHERE THE MAGIC HAPPENS.",
      intro: [
        "Creativiteit zonder strategie wordt ruis. Strategie zonder creativiteit wordt saai.",
        "Wij doen niet aan kiezen tussen die twee. Wij brengen ze samen — en dáár gebeurt het.",
      ],
      blocksTitle: "Waar strategie over gaat",
      blocks: [
        { h: "Positionering", p: "Wat ben jij dat niemand anders is? En durf je dat ook te zeggen? Wij zoeken de plek in het hoofd van je klant die nog vrij is — en claimen ze." },
        { h: "Merkstrategie", p: "Waarom je bestaat, wat je belooft en hoe je dat consequent waarmaakt. De basis waarop elk creatief idee getoetst wordt." },
        { h: "Marketingstrategie", p: "Wie, wanneer, waar en met welke boodschap. Niet alles voor iedereen. Het juiste voor de juiste mensen." },
        { h: "Digitale strategie", p: "Welke rol speelt je website, je content, je data, AI? Niet “omdat het moet”, maar omdat het je klant iets oplevert." },
        { h: "Doelgroep en customer journey", p: "Hoe beslist iemand echt? Waar twijfelt hij, waar haakt hij af, waar overtuig je hem? Wij tekenen het pad en bouwen op de punten die het verschil maken." },
        { h: "Richting en groei", p: "Strategie zegt ook wat je níét doet. Dat is vaak het moeilijkste — en het meest waardevolle." },
      ],
      closer: ["Een goede strategie voel je niet in het plan.", "Je voelt hem in alles wat erna komt."],
      cta: "Praat over je idee",
      meta: "Positionering, merk-, marketing- en digitale strategie door Defy & Brand Events. Creativiteit zonder strategie wordt ruis; strategie zonder creativiteit wordt saai. Wij brengen beide samen.",
    },
    {
      slug: "brand-creative",
      num: "02",
      name: "Brand & Creative",
      role: "geeft het idee vorm",
      headline: "YOUR BRAND DESERVES MORE THAN “GOOD ENOUGH”.",
      intro: [
        "Er zijn genoeg merken die er goed uitzien. Er zijn er weinig die je herkent met je ogen half dicht.",
        "Een merk moet niet alleen mooi zijn. Het moet herkenbaar zijn. Een gevoel oproepen. Een positie innemen. Iets betekenen.",
        "Creativiteit zonder betekenis is decoratie. Wij maken geen decoratie.",
      ],
      blocksTitle: "Wat wij bouwen",
      blocks: [
        { h: "Brand identity", p: "Wie je bent, waar je voor staat en waarom iemand dat zou moeten voelen. Het fundament onder alles wat je daarna maakt." },
        { h: "Visual identity", p: "Logo, kleur, typografie, beeld, beweging — als één systeem dat overal herkenbaar terugkomt. Van je website tot je e-mailhandtekening." },
        { h: "Creative direction", p: "De rode draad. Wij bewaken dat elk beeld, elke campagne en elke pagina hetzelfde merk ademt, ook als tien verschillende mensen eraan werken." },
        { h: "Concepten", p: "Het idee vóór de uitvoering. Groot genoeg om een jaar campagne te dragen, scherp genoeg om in één zin te passen." },
        { h: "Campagnes", p: "Creatief werk dat een positie inneemt. Niet iedereen hoeft het leuk te vinden. De juiste mensen moeten het onthouden." },
        { h: "Art direction", p: "Fotografie, film, illustratie, motion — geregisseerd zodat het beeld zegt wat de woorden niet hoeven te zeggen." },
        { h: "Visual storytelling", p: "Een merk vertelt een verhaal, ook als het zwijgt. Wij zorgen dat het het juiste verhaal is." },
      ],
      closer: ["“Goed genoeg” wordt vergeten voor de pagina geladen is.", "Wij bouwen merken die blijven plakken."],
      cta: "Laten we iets bouwen",
      meta: "Brand identity, visual identity, creative direction en campagnes door Defy & Brand Events. Creativiteit zonder betekenis is decoratie — wij maken geen decoratie.",
    },
    {
      slug: "copywriting",
      num: "03",
      name: "Copywriting",
      role: "geeft het een stem",
      headline: "WORDS THAT MOVE PEOPLE.",
      intro: [
        "Informatie is gratis. Aandacht niet. Goede copy geeft geen uitleg. Ze zorgt dat iemand wil weten hoe het verder gaat.",
        "Wij schrijven geen teksten. Wij vinden de woorden die een idee laten landen.",
      ],
      listTitle: "Wat woorden doen",
      list: [
        "Goede woorden trekken aandacht.",
        "Maken in één zin duidelijk wat een pagina nodig had.",
        "Bouwen verlangen waar eerst onverschilligheid was.",
        "Geven een merk een stem die je herkent zonder logo.",
        "En zetten mensen aan tot de actie die je bedoelde.",
      ],
      blocksTitle: "Waarvoor wij schrijven",
      blocks: [
        { h: "Websites", p: "Headlines die stoppen, structuur die leidt, microcopy die geruststelt op het moment dat iemand twijfelt." },
        { h: "Campagnes", p: "Eén idee, één zin, en de discipline om er niets aan toe te voegen." },
        { h: "Branding", p: "Manifesten, taglines, de zinnen die je team gaat herhalen zonder dat het moet." },
        { h: "Social media", p: "Kort, eigen en menselijk. Geschreven voor een duim die scrolt, niet voor een jury." },
        { h: "Storytelling", p: "Het verhaal achter het product — verteld zodat het blijft hangen, niet zodat het lang is." },
        { h: "Tone of voice", p: "Hoe klinkt je merk als het boos is, blij, geruststellend? Wij leggen het vast zodat iedereen die schrijft, hetzelfde merk schrijft." },
        { h: "Messaging", p: "Wat zeg je eerst, wat daarna, en wat zeg je nooit. De hiërarchie die elke communicatie scherper maakt." },
        { h: "Conversion copy", p: "De woorden op de knop, in de mail, op de laatste pagina. Klein in omvang, groot in effect." },
      ],
      closer: ["Elk woord op je site kost iemand een halve seconde.", "Wij zorgen dat het die waard is."],
      cta: "Vertel ons wat je wilt zeggen",
      meta: "Copywriting voor websites, campagnes, branding en social door Defy & Brand Events. Wij schrijven geen teksten; wij vinden de woorden die een idee laten landen.",
    },
    {
      slug: "website-design",
      num: "04",
      name: "Website Design",
      role: "bouwt de digitale ervaring",
      headline: "DON'T BUILD A WEBSITE. BUILD THE MOMENT THEY DECIDE TO STAY.",
      sub: "We don't design pages. We design the experience between the first click and the next decision.",
      intro: [
        "Iemand komt op je site. Drie seconden later weet die persoon of hij blijft. Niet omdat hij je tekst gelezen heeft. Omdat hij iets gevoeld heeft: dit is goed, dit klopt, hier wil ik verder.",
        "Dat moment ontwerpen wij.",
      ],
      listTitle: "Wat een website moet doen",
      list: [
        "Een mooie website is het minimum. Een goede website doet iets.",
        "Hij pakt aandacht voor je iets moet uitleggen.",
        "Hij bouwt vertrouwen zonder het te vragen.",
        "Hij maakt nieuwsgierig naar de volgende scroll.",
        "Hij laat mensen blijven.",
        "En op het juiste moment laat hij ze kiezen.",
      ],
      blocksTitle: "Hoe wij bouwen",
      blocks: [
        { h: "Ervaring, geen pagina's", p: "Wij denken in scènes, niet in secties. Wat ziet iemand eerst? Wat beweegt? Wat gebeurt er als hij scrolt, klikt, twijfelt? Elke overgang is een kans om iets te zeggen zonder woorden." },
        { h: "UX/UI die uit de weg gaat", p: "Goede interface merk je niet. Je merkt dat het makkelijk was. Wij ontwerpen paden, niet obstakels — en testen ze tot ze vanzelf gaan." },
        { h: "Storytelling in structuur", p: "Een website is een verhaal met een volgorde. Wij bepalen wat wanneer landt, zodat de bezoeker aan het einde precies weet wie je bent en waarom dat ertoe doet." },
        { h: "Conversie zonder trucjes", p: "Geen valse urgentie, geen dark patterns. Wel: de juiste vraag op het juiste moment, aan iemand die al overtuigd is." },
        { h: "Interaction & motion", p: "Beweging is geen versiering. Het is de manier waarop een site laat voelen wat hij bedoelt. Wij zetten het in waar het richting geeft — en laten het weg waar het afleidt." },
        { h: "Responsive, altijd", p: "Op een telefoon in de trein moet het even sterk voelen als op een groot scherm in een vergaderzaal. Dat is geen aanpassing achteraf. Dat is het ontwerp." },
        { h: "Performance is ook een gevoel", p: "Een site die wacht, verliest. Wij bouwen licht en snel — omdat traagheid het eerste is wat iemand voelt en het laatste wat hij vergeeft." },
        { h: "Brand experience", p: "Je website is de plek waar je merk het meest zichzelf mag zijn. Wij zorgen dat elke pixel dat ook is." },
      ],
      closer: ["Een website is af als hij iets doet met de mensen die hem bezoeken.", "Tot dan is het een bestand."],
      cta: "Bouw het moment",
      meta: "Website design, UX/UI en digitale ervaring door Defy & Brand Events. Don't build a website. Build the moment they decide to stay.",
    },
    {
      slug: "marketing",
      num: "05",
      name: "Marketing",
      role: "brengt de juiste mensen ernaartoe",
      headline: "MARKETING IS OUR DNA.",
      sub: "People don't remember ads. They remember how you made them feel.",
      intro: [
        "Niemand onthoudt je campagne. Mensen onthouden wat ze erbij voelden — en dat gevoel beslist later, in de winkel, op je site, in een gesprek.",
        "Marketing is voor ons geen zichtbaarheid kopen. Het is perceptie vormen en gedrag beïnvloeden. Bewust, meetbaar, en met respect voor de mens aan de andere kant.",
      ],
      blocksTitle: "Hoe wij marketing zien",
      blocks: [
        { h: "Strategie eerst", p: "Wie moet iets voelen? Wat moet die persoon daarna doen? Pas als dat scherp is, beginnen we te maken. Anders maken we ruis." },
        { h: "Doelgroep is geen segment. Het is een mens.", p: "Met een dag, een context en een reden om je te negeren. Wij zoeken het moment waarop hij dat niet doet." },
        { h: "Campagnes die één ding zeggen", p: "Sterke campagnes zijn niet vol. Ze zijn scherp. Eén idee, uitgevoerd op elk kanaal alsof het daar thuishoort." },
        { h: "Content die verdient gezien te worden", p: "Niet omdat het algoritme het duwt. Omdat mensen het willen. Dat is het verschil tussen bereik en aandacht." },
        { h: "Performance en data", p: "Elke euro heeft een reden en een resultaat. Wij meten wat ertoe doet — niet wat er mooi uitziet in een rapport — en sturen bij terwijl het loopt." },
        { h: "De hele customer journey", p: "Van de eerste indruk tot de herhaalde aankoop. Marketing stopt niet bij de klik. Het stopt bij het gedrag dat je wilde zien." },
        { h: "Groei die blijft", p: "Snel groeien kan iedereen met genoeg budget. Wij bouwen aan groei die overeind blijft als de campagne stopt." },
      ],
      closer: ["Goede marketing verandert niet wat mensen zien.", "Het verandert wat ze denken als ze het zien."],
      cta: "Maak je zet",
      meta: "Marketing als combinatie van strategie, creativiteit, content, performance en data. Defy & Brand Events beïnvloedt perceptie en gedrag — niet enkel zichtbaarheid.",
    },
    {
      slug: "seo",
      num: "06",
      name: "SEO",
      role: "maakt je vindbaar",
      headline: "Gevonden worden is één ding. Gevonden worden door de juiste persoon op het juiste moment is iets anders.",
      intro: [
        "SEO is geen lijstje keywords en een plek in Google. Het is begrijpen wat mensen zoeken, waarom ze het zoeken en wat ze verwachten te vinden — en dan de beste plek zijn om te landen.",
      ],
      blocksTitle: "Hoe wij SEO aanpakken",
      blocks: [
        { h: "Zoekintentie voor zoekwoorden", p: "Achter elke zoekopdracht zit een mens met een vraag. Wij beginnen bij de vraag, niet bij het woord." },
        { h: "Relevantie", p: "Ranken op iets wat je niet levert, kost je bezoekers én vertrouwen. Wij richten ons op de zoekopdrachten die écht bij je passen." },
        { h: "Content die het antwoord is", p: "Geen tekst om tekst te hebben. Pagina's die de vraag beter beantwoorden dan wie ook — daar houdt Google van, omdat mensen ervan houden." },
        { h: "Technische basis", p: "Snelheid, structuur, mobiel, indexeerbaarheid. Onzichtbaar voor de bezoeker, beslissend voor het resultaat." },
        { h: "Autoriteit", p: "Betrouwbaarheid bouw je op, niet in. Wij werken aan de signalen die zeggen: dit merk weet waar het over spreekt." },
        { h: "Zichtbaarheid die converteert", p: "Verkeer is geen doel. Wij meten wat die bezoekers dóen — en optimaliseren daarop." },
      ],
      closer: ["De beste positie in Google is er één waarbij de bezoeker denkt: precies dit zocht ik."],
      cta: "Word gevonden door de juiste mensen",
      meta: "SEO door Defy & Brand Events: zoekintentie, relevantie, content, technische basis, autoriteit en conversie. Gevonden worden door de juiste persoon op het juiste moment.",
    },
    {
      slug: "geo",
      num: "07",
      name: "GEO",
      role: "maakt je begrijpelijk voor AI",
      headline: "IF AI DOESN'T UNDERSTAND YOU, IT CAN'T RECOMMEND YOU.",
      intro: [
        "Steeds meer mensen zoeken niet meer. Ze vragen. Aan ChatGPT, Gemini, Copilot, Perplexity. “Welke agency past bij mijn project?” “Welk product doet dit het best?” “Wie kan mij hiermee helpen?”",
        "En het antwoord komt niet van een lijst met tien blauwe links. Het komt van een AI die beslist welke bedrijven, producten en oplossingen relevant lijken — en die noemt.",
        "GEO (Generative Engine Optimization) gaat over die beslissing. Het zorgt dat AI-systemen begrijpen wie je bent, wat je doet en voor wie je het doet — zodat je in aanmerking kómt.",
      ],
      listTitle: "Waarom het ertoe doet",
      list: [
        "Een AI leest je website anders dan een mens. Hij zoekt duidelijkheid, samenhang en bewijs.",
        "Vage beloftes en marketingtaal helpen hem niet. Concrete, betrouwbare en consistente informatie wel.",
        "Wie onduidelijk is, wordt niet verkeerd begrepen. Hij wordt overgeslagen.",
      ],
      blocksTitle: "Hoe wij werken aan GEO",
      blocks: [
        { h: "Duidelijkheid", p: "Wat je doet, voor wie en waarom dat anders is — in taal die een machine én een mens in één keer begrijpt." },
        { h: "Structuur", p: "Informatie zo opgebouwd dat een AI ze kan lezen, verbinden en correct citeren. Van pagina-opbouw tot gestructureerde data." },
        { h: "Consistentie", p: "Dezelfde feiten op je site, in je profielen en in wat anderen over je schrijven. Tegenstrijdigheden zijn voor een AI een reden om te twijfelen." },
        { h: "Betrouwbaarheid", p: "Bronnen, cijfers, cases, context. Hoe meer een AI kan verifiëren, hoe eerder hij je serieus neemt." },
        { h: "Relevantie", p: "Aansluiten bij de vragen die jouw klanten écht stellen — niet bij de termen die jij intern gebruikt." },
      ],
      honest: {
        h: "Eerlijk over wat GEO is",
        p: "GEO geeft geen garantie dat een AI je aanbeveelt. Niemand kan dat beloven — die systemen beslissen zelf. Wat GEO wél doet: zorgen dat je begrepen wordt. En wie begrepen wordt, kan gekozen worden.",
      },
      closer: ["Wie begrepen wordt, kan gekozen worden."],
      cta: "Laat AI je begrijpen",
      meta: "GEO (Generative Engine Optimization) door Defy & Brand Events: duidelijke, gestructureerde en betrouwbare informatie zodat AI-systemen als ChatGPT, Gemini en Perplexity je begrijpen. Zonder valse garanties.",
    },
    {
      slug: "agent-ready",
      num: "08",
      name: "Agent Ready",
      role: "maakt je klaar voor AI agents",
      headline: "Begrijpelijk voor mensen. Leesbaar voor machines.",
      intro: [
        "Tot nu toe bezochten mensen je website. Binnenkort doen AI agents dat ook — en steeds vaker in hun plaats.",
        "Een agent is software die een opdracht krijgt en die zelfstandig uitvoert: informatie zoeken, aanbieders vergelijken, prijzen interpreteren, een afspraak vastleggen, een offerte aanvragen. Zonder dat er een mens meekijkt op elk scherm.",
        "Als die agent jouw website niet begrijpt, gaat hij naar de volgende.",
      ],
      blocksTitle: "Wat Agent Ready betekent",
      blocks: [
        { h: "Duidelijke informatie", p: "Wat je aanbiedt, wat het kost, waar je actief bent, hoe je bereikbaar bent — zonder dat iemand het moet afleiden uit een sfeerfoto." },
        { h: "Gestructureerde content", p: "Informatie in een vorm die machines herkennen: consistent, gelabeld, op een logische plek. Voor een mens onzichtbaar. Voor een agent het verschil tussen begrijpen en raden." },
        { h: "Betrouwbare bedrijfsgegevens", p: "Openingsuren, adressen, contactgegevens, producten — één versie van de waarheid, overal hetzelfde." },
        { h: "Digitale toegankelijkheid", p: "Wat toegankelijk is voor mensen met een beperking, is meestal ook leesbaar voor machines. Het zijn dezelfde principes: helderheid, structuur, geen verrassingen." },
        { h: "Machine-readable content", p: "Je site spreekt twee talen tegelijk: die van je klant en die van de systemen die je klant gebruikt." },
        { h: "AI discoverability", p: "Gevonden, begrepen en correct weergegeven worden in de tools waar je klanten steeds vaker beginnen." },
      ],
      closer: [
        "Agent Ready is ervoor zorgen dat je bedrijf ook bestaat op de plek waar beslissingen steeds vaker beginnen: in een gesprek tussen een mens en een machine.",
      ],
      cta: "Check of je klaar bent",
      meta: "Agent Ready door Defy & Brand Events: duidelijke, gestructureerde en betrouwbare bedrijfsinformatie zodat AI agents je website begrijpen en correct weergeven.",
    },
    {
      slug: "agentic-workflow",
      num: "09",
      name: "Agentic Workflow",
      role: "laat technologie handelen",
      headline: "Van AI gebruiken naar AI laten werken.",
      intro: [
        "De meeste bedrijven gebruiken AI om sneller te schrijven of ideeën te genereren. Nuttig. Maar het is een eerste stap.",
        "De volgende stap is AI die iets dóet. Die een proces ondersteunt, een beslissing voorbereidt, een actie uitvoert — en daarvan leert. Dat noemen wij een agentic workflow.",
      ],
      steps: [
        { k: "Trigger", p: "Er gebeurt iets: een aanvraag komt binnen, een klant twijfelt, een voorraad daalt, een dag begint." },
        { k: "Think", p: "De agent verzamelt wat hij nodig heeft — context, data, regels — en begrijpt de situatie." },
        { k: "Decide", p: "Hij kiest de beste volgende stap. Zelfstandig waar dat kan, met een mens erbij waar dat moet." },
        { k: "Act", p: "Hij voert uit: een mail, een update in je systeem, een offerte, een planning, een waarschuwing." },
        { k: "Measure", p: "Wat gebeurde er daarna? Werkte het? Hoe snel, hoe goed?" },
        { k: "Improve", p: "De volgende keer doet hij het beter. Niet omdat iemand het hem zegt, maar omdat hij het gezien heeft." },
      ],
      blocksTitle: "Waar het zin heeft",
      blocks: [
        { h: "Leadopvolging", p: "Die nooit een dag laat liggen." },
        { h: "Content", p: "Die op het juiste moment klaarstaat." },
        { h: "Klantvragen", p: "Die om drie uur 's nachts een goed antwoord krijgen." },
        { h: "Rapporten", p: "Die zichzelf schrijven en een advies meegeven." },
        { h: "Processen", p: "Die niet langer wachten op degene die toevallig het wachtwoord kent." },
      ],
      honest: {
        h: "Onze regel",
        p: "Technologie is alleen interessant als ze werk beter, sneller of slimmer maakt. Anders is het een demo. Wij bouwen geen AI om AI te hebben. Wij zoeken de plek in je bedrijf waar een intelligente workflow tijd, fouten of frustratie wegneemt — en bouwen precies dat.",
      },
      closer: ["Technologie is alleen interessant als ze werk beter, sneller of slimmer maakt.", "Anders is het een demo."],
      cta: "Laat technologie werken",
      meta: "Agentic workflows, AI agents en automatisering door Defy & Brand Events. Trigger. Think. Decide. Act. Measure. Improve. Van AI gebruiken naar AI laten werken.",
    },
  ],
};
